services:
  db:
    image: postgres:16-alpine
    container_name: cricket_db
    environment:
      POSTGRES_DB: cricket_academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cricket-network

  backend:
    image: thamaraikannans/cricket-backend:latest
    build:
      context: ./backend-springboot
      dockerfile: Dockerfile
    container_name: cricket_backend
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/cricket_academy
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      HIBERNATE_DDL_AUTO: update
      SHOW_SQL: "true"
    ports:
      - "8080:8080"
    networks:
      - cricket-network
    depends_on:
      - db

  frontend:
    image: thamaraikannans/cricket-frontend:latest
    build: 
      context: ./frontend-python
      dockerfile: Dockerfile
    container_name: cricket_frontend
    environment:
      BACKEND_BASE_URL: http://backend:8080/api
    ports:
      - "12345:5000"
    networks:
      - cricket-network
    depends_on:
      - backend

volumes:
  db-data:

networks:
  cricket-network:
    driver: bridge
